// Custom Cloudflare Worker entrypoint.
//
// `opennextjs-cloudflare build` generates `.open-next/worker.js`, an HTTP
// `fetch` handler for the Next.js app. Cloudflare Cron Triggers invoke a
// `scheduled` handler, which that generated worker does NOT provide. So we wrap
// it here: delegate `fetch` to OpenNext untouched, and add a `scheduled`
// handler that runs the due-post publisher (`/api/social/publish-due`).
//
// `wrangler.jsonc` points `main` at this file. The `.open-next/worker.js`
// import only exists after the build step, so the type errors below are
// expected and suppressed; this file is excluded from `tsc`/eslint.

// @ts-expect-error - generated by `opennextjs-cloudflare build`, absent until then
import openNextHandler from './.open-next/worker.js'

interface CronEnv {
  NEXT_PUBLIC_APP_URL?: string
  CRON_SECRET?: string
}

const PUBLISH_DUE_PATH = '/api/social/publish-due'
const FALLBACK_BASE_URL = 'https://kaida1.ycatesting.com'

export default {
  fetch(request: Request, env: CronEnv, ctx: ExecutionContext): Response | Promise<Response> {
    return openNextHandler.fetch(request, env, ctx)
  },

  async scheduled(_controller: ScheduledController, env: CronEnv, ctx: ExecutionContext): Promise<void> {
    const baseUrl = env.NEXT_PUBLIC_APP_URL ?? FALLBACK_BASE_URL

    const headers: Record<string, string> = {}
    if (env.CRON_SECRET) headers.Authorization = `Bearer ${env.CRON_SECRET}`

    const request = new Request(new URL(PUBLISH_DUE_PATH, baseUrl), { method: 'GET', headers })

    // Run inside the worker via the OpenNext handler (no extra public hop) and
    // keep the invocation alive until publishing completes. Errors are logged
    // inside the route itself.
    ctx.waitUntil(
      Promise.resolve(openNextHandler.fetch(request, env, ctx)).catch(() => {})
    )
  },
}

// Re-export any Durable Object / named exports OpenNext registers so their
// Worker bindings continue to resolve through this custom entrypoint.
// @ts-expect-error - generated by `opennextjs-cloudflare build`, absent until then
export * from './.open-next/worker.js'
