import { Clock, Sparkles } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Section, EmptyState } from '@/components/analytics/data-source'
import { getBestTimes, NETWORKS, REAL_NETWORKS, type Network } from '@/app/(dashboard)/analytics/mock-data'
import { NETWORK_LABEL, NETWORK_ICON } from '@/components/analytics/network-meta'
import { sourceSuffix } from '@/lib/analytics/format'
import { ALLOW_MOCK_ANALYTICS } from '@/lib/analytics/config'

export function BestTimes({ network }: { network: Network }) {
  // When viewing "All", show recommended windows per platform; otherwise show
  // the selected platform's windows.
  const platforms = network === 'all' ? REAL_NETWORKS : [network]
  const networkLabel = NETWORKS.find((n) => n.id === network)?.label ?? 'All'

  return (
    <Section
      title="Best time to post"
      icon={Clock}
      source={`Claude AI over scheduled_posts history ${sourceSuffix(ALLOW_MOCK_ANALYTICS ? 'mock' : 'empty')}`}
      description="Recommended posting windows generated by Claude from your past engagement, per platform."
    >
      {!ALLOW_MOCK_ANALYTICS ? (
        <EmptyState message="Best-time recommendations appear once you have published posts with engagement history." />
      ) : (
      <Card>
        <CardContent className="flex flex-col gap-4">
          <p className="inline-flex items-center gap-1.5 text-sm text-muted-foreground">
            <Sparkles className="size-4" />
            Claude analyzed your engagement history for{' '}
            <span className="font-medium text-foreground">{networkLabel}</span> and recommends:
          </p>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {platforms.map((p) => {
              const Icon = NETWORK_ICON[p]
              const slots = getBestTimes(p)
              return (
                <div key={p} className="flex flex-col gap-2.5 rounded-lg border border-border p-3">
                  <div className="flex items-center gap-2 text-sm font-medium">
                    <Icon className="size-4" />
                    {NETWORK_LABEL[p]}
                  </div>
                  <div className="flex flex-col gap-2">
                    {slots.map((slot) => (
                      <div key={`${slot.day}-${slot.time}`} className="flex items-center gap-3">
                        <span className="w-24 shrink-0 text-sm">
                          {slot.day} · {slot.time}
                        </span>
                        <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted">
                          <div
                            className="h-full rounded-full bg-[var(--chart-3)]"
                            style={{ width: `${slot.score}%` }}
                          />
                        </div>
                        <span className="w-8 shrink-0 text-right text-xs tabular-nums text-muted-foreground">
                          {slot.score}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )
            })}
          </div>
        </CardContent>
      </Card>
      )}
    </Section>
  )
}
